env:
  global:
    - DB=mysql

os:
  - linux

before_deploy: "echo 'ready?'"

deploy:
  - provider: codedeploy
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "S3 Bucket"
    key: latest/MyApp.zip
    application: MyApp
    deployment_group: MyDeploymentGroup

after_deploy:
  - ./after_deploy_1.sh
  - ./after_deploy_2.sh
  
notifications:
  pushover:
    api_key: "12345"
    users:
      - "mona"
